python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_GOBP PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_GOBP PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_GOBP PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_GOBP PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_HPO PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_HPO PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_HPO PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_NCM_NCV_Per0_PerGene_HPO PhyloP Outputs_Combined/PhyloP 100

python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_GOBP PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_GOBP PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_GOBP PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_GOBP PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_HPO PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_HPO PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_HPO PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCM_NCV_Per0_PerGene_HPO PhyloP Outputs_Combined/PhyloP 100

python compute_z_and_p.py Outputs/PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCMHCOnly_NCV_Per0_PerGene PhyloP_NC_FiltWGS_PhyloP-100_SpecSup250_YCMHCOnly_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
python compute_z_and_p.py Outputs/PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCMHCOnly_NCV_Per0_PerGene PhyloP_NC_NoFiltWGS_PhyloP-100_SpecSup250_YCMHCOnly_NCV_Per0_PerGene PhyloP Outputs_Combined/PhyloP 100
